/**
 * services/detour-planner.js
 * 
 * Client-side detour planning for routes with failed jumps.
 * Processes route data received from worker and computes alternative paths.
 * 
 * Strategy:
 * - Treat original route as immutable
 * - Build enhanced "display route" with detour annotations
 * - Use physics-based jumpable distance calculations
 * - Mark systems as excluded, detour, or no-detour-available
 * 
 * @module detour-planner
 */

import { fetchBatchSystems } from '../core/api-client.js';
import { normalizeSystemName } from '../core/normalization.js';

const MAX_TOTAL_HEAT = 149;
const DETOUR_HEAT_THRESHOLD = 140;

/**
 * Calculate maximum jump distance based on heat budget
 * @param {number} currentHeat - Current heat level  
 * @param {number} totalMass - Total ship mass
 * @param {number} effectiveC - Effective C-value
 * @param {number} hullMass - Hull mass
 * @param {number} maxHeat - Maximum allowed heat (default 149)
 * @returns {number} Maximum jumpable distance in LY
 */
function calculateMaxJumpDistance(currentHeat, totalMass, effectiveC, hullMass, maxHeat = MAX_TOTAL_HEAT) {
  if (currentHeat >= maxHeat) return 0;
  const heatBudget = maxHeat - currentHeat;
  return (heatBudget * effectiveC * hullMass) / (3 * totalMass);
}

/**
 * Calculate jump heat generation
 * @param {number} distanceLY - Jump distance in light years
 * @param {number} totalMass - Total ship mass
 * @param {number} effectiveC - Effective C-value  
 * @param {number} hullMass - Hull mass
 * @returns {number} Heat generated by jump
 */
function calculateJumpHeat(distanceLY, totalMass, effectiveC, hullMass) {
  if (!distanceLY || !totalMass || !effectiveC || !hullMass) return null;
  return (3 * totalMass * distanceLY) / (effectiveC * hullMass);
}

/**
 * Calculate 3D distance between two coordinates in light years
 * @param {object} coords1 - First system coordinates {x, y, z}
 * @param {object} coords2 - Second system coordinates {x, y, z}
 * @returns {number|null} Distance in LY or null if invalid
 */
function calculateDistance(coords1, coords2) {
  if (!coords1 || !coords2) return null;
  if (!coords1.x || !coords2.x) return null;
  
  const METERS_PER_LY = 9.46073e15;
  const dx = coords1.x - coords2.x;
  const dy = coords1.y - coords2.y;
  const dz = coords1.z - coords2.z;
  const distM = Math.sqrt(dx * dx + dy * dy + dz * dz);
  return distM / METERS_PER_LY;
}

/**
 * Find viable detour system to bypass a failed jump
 * @param {number} failedIndex - Index in route where jump fails
 * @param {array} routeData - Current route array
 * @param {object} shipParams - Ship configuration {totalMass, hullMass, effectiveC}
 * @param {object} systemDatabase - Map of system names to system data
 * @returns {object|null} Detour plan or null if no viable detour found
 */
async function planDetour(failedIndex, routeData, shipParams, systemDatabase) {
  if (failedIndex < 1 || failedIndex >= routeData.length) return null;
  
  const { totalMass, hullMass, effectiveC } = shipParams;
  
  const prevSystem = routeData[failedIndex - 1];
  const failedSystem = routeData[failedIndex];
  const nextSystem = failedIndex + 1 < routeData.length ? routeData[failedIndex + 1] : null;
  
  // Get system data from database
  const prevData = systemDatabase[normalizeSystemName(prevSystem.name)];
  const failedData = systemDatabase[normalizeSystemName(failedSystem.name)];
  
  if (!prevData || !failedData || !prevData.coords) return null;
  
  // Calculate maximum jumpable distance from previous system
  const maxJumpDistance = calculateMaxJumpDistance(
    prevSystem.low_heat,
    totalMass,
    effectiveC,
    hullMass,
    DETOUR_HEAT_THRESHOLD
  );
  
  if (maxJumpDistance <= 0) return null;
  
  // Collect candidate detour systems within jumpable radius
  const candidates = [];
  const routeSystemNames = new Set(routeData.map(r => normalizeSystemName(r.name)));
  
  for (const [systemName, systemData] of Object.entries(systemDatabase)) {
    // Skip route systems
    if (routeSystemNames.has(systemName)) continue;
    
    // Check distance from previous system
    const distFromPrev = calculateDistance(prevData.coords, systemData.coords);
    if (!distFromPrev || distFromPrev > maxJumpDistance) continue;
    
    // Calculate jump to candidate
    const jumpHeat = calculateJumpHeat(distFromPrev, totalMass, effectiveC, hullMass);
    if (!jumpHeat) continue;
    
    const totalHeat = prevSystem.low_heat + jumpHeat;
    if (totalHeat >= DETOUR_HEAT_THRESHOLD) continue;
    
    // Try to rejoin at next system (if exists)
    let rejoinIndex = null;
    let rejoinDistance = null;
    let rejoinJumpHeat = null;
    let rejoinTotalHeat = null;
    
    if (nextSystem) {
      const nextData = systemDatabase[normalizeSystemName(nextSystem.name)];
      if (nextData && nextData.coords) {
        rejoinDistance = calculateDistance(systemData.coords, nextData.coords);
        if (rejoinDistance) {
          rejoinJumpHeat = calculateJumpHeat(rejoinDistance, totalMass, effectiveC, hullMass);
          if (rejoinJumpHeat) {
            rejoinTotalHeat = systemData.coldest.heat + rejoinJumpHeat;
            if (rejoinTotalHeat && rejoinTotalHeat < DETOUR_HEAT_THRESHOLD) {
              rejoinIndex = failedIndex + 1;
            }
          }
        }
      }
    }
    
    // If can't rejoin at next, try system after that
    if (!rejoinIndex && failedIndex + 2 < routeData.length) {
      const nextNextSystem = routeData[failedIndex + 2];
      const nextNextData = systemDatabase[normalizeSystemName(nextNextSystem.name)];
      if (nextNextData && nextNextData.coords) {
        rejoinDistance = calculateDistance(systemData.coords, nextNextData.coords);
        if (rejoinDistance) {
          rejoinJumpHeat = calculateJumpHeat(rejoinDistance, totalMass, effectiveC, hullMass);
          if (rejoinJumpHeat) {
            rejoinTotalHeat = systemData.coldest.heat + rejoinJumpHeat;
            if (rejoinTotalHeat && rejoinTotalHeat < DETOUR_HEAT_THRESHOLD) {
              rejoinIndex = failedIndex + 2;
            }
          }
        }
      }
    }
    
    // Must be able to rejoin route
    if (!rejoinIndex) continue;
    
    candidates.push({
      systemName,
      systemData,
      distFromPrev,
      jumpHeat,
      totalHeat,
      rejoinIndex,
      rejoinDistance,
      rejoinJumpHeat,
      rejoinTotalHeat,
      // Score: prefer shorter total detour distance
      score: distFromPrev + (rejoinDistance || 0)
    });
  }
  
  if (candidates.length === 0) return null;
  
  // Sort by score (shorter detour preferred)
  candidates.sort((a, b) => a.score - b.score);
  
  const best = candidates[0];
  
  return {
    detourSystemName: best.systemName,
    detourSystemData: best.systemData,
    insertAfterIndex: failedIndex - 1,
    rejoinAtIndex: best.rejoinIndex,
    jumpToDetour: {
      distance_ly: best.distFromPrev,
      jump_heat_gen: best.jumpHeat,
      total_after_jump: best.totalHeat,
      gate: null
    },
    jumpFromDetour: {
      distance_ly: best.rejoinDistance,
      jump_heat_gen: best.rejoinJumpHeat,
      total_after_jump: best.rejoinTotalHeat,
      gate: null
    }
  };
}

/**
 * Apply detours to route data
 * Marks failed systems as excluded and inserts detour systems
 * 
 * @param {array} routeData - Route array with jump analysis
 * @param {array} results - Search results with system data
 * @param {object} shipParams - Ship configuration {totalMass, hullMass, effectiveC}
 * @returns {Promise<array>} Enhanced route with detours
 */
async function applyDetours(routeData, results, shipParams) {
  // Build system database from results
  const systemDatabase = {};
  for (const result of results) {
    if (!result.error && result.system) {
      const name = normalizeSystemName(result.system.name);
      systemDatabase[name] = result.system;
    }
  }
  
  // Find all failed jumps
  const failures = [];
  for (let i = 1; i < routeData.length; i++) {
    const entry = routeData[i];
    if (entry.can_jump === false && !entry.gate) {
      failures.push(i);
    }
  }
  
  if (failures.length === 0) return routeData;
  
  // Process failures
  const enhancedRoute = [...routeData];
  let insertionOffset = 0;
  
  for (const failedIndex of failures) {
    const adjustedIndex = failedIndex + insertionOffset;
    
    const detourPlan = await planDetour(failedIndex, routeData, shipParams, systemDatabase);
    
    if (detourPlan) {
      // Mark failed system as excluded
      enhancedRoute[adjustedIndex]._excluded = true;
      
      // Mark next systems as excluded if detour skips them
      if (detourPlan.rejoinAtIndex > failedIndex + 1) {
        for (let i = failedIndex + 1; i < detourPlan.rejoinAtIndex; i++) {
          enhancedRoute[i + insertionOffset]._excluded = true;
        }
      }
      
      // Create detour system entry
      const detourSystem = {
        name: detourPlan.detourSystemName,
        id: detourPlan.detourSystemData.id,
        low_heat: detourPlan.detourSystemData.coldest.heat,
        status: detourPlan.detourSystemData.status,
        distance_ly: detourPlan.jumpToDetour.distance_ly,
        jump_heat_gen: detourPlan.jumpToDetour.jump_heat_gen,
        total_after_jump: detourPlan.jumpToDetour.total_after_jump,
        can_jump: true,
        gate: null,
        _detour: true,
        _detourRejoinDistance: detourPlan.jumpFromDetour.distance_ly,
        _detourRejoinHeat: detourPlan.jumpFromDetour.jump_heat_gen
      };
      
      // Insert detour after previous system
      enhancedRoute.splice(adjustedIndex, 0, detourSystem);
      insertionOffset++;
      
      // Update next jump data (from detour to rejoin point)
      const rejoinIndex = detourPlan.rejoinAtIndex + insertionOffset;
      if (rejoinIndex < enhancedRoute.length) {
        enhancedRoute[rejoinIndex].distance_ly = detourPlan.jumpFromDetour.distance_ly;
        enhancedRoute[rejoinIndex].jump_heat_gen = detourPlan.jumpFromDetour.jump_heat_gen;
        enhancedRoute[rejoinIndex].total_after_jump = detourPlan.jumpFromDetour.total_after_jump;
        enhancedRoute[rejoinIndex].can_jump = detourPlan.jumpFromDetour.total_after_jump < DETOUR_HEAT_THRESHOLD;
        enhancedRoute[rejoinIndex].gate = null;
      }
    } else {
      // No detour found - mark system with diagnostic flag
      enhancedRoute[adjustedIndex]._noDetourAvailable = true;
    }
  }
  
  return enhancedRoute;
}

export { applyDetours, calculateMaxJumpDistance, calculateJumpHeat };
